ding dong bot demo
wechaty/wechaty-puppet-whatsapp pull request #2
Opened 2020-10-03 15:49 UTC by univerone

2020-10-04 06:57 UTC, huan approved these changes
Thank your very much for this great work! The WhatsApp puppet is very valuable and let's keep improving it!

LGTM

2020-10-04 06:57 UTC, huan commented on tsconfig.json
> +    "esModuleInterop": true
I believe there's already this options in our @chatie/tsconfig ?

2020-10-04 06:57 UTC, huan commented on package.json
> +    "faker": "^5.1.0",
We don't need faker anymore.

2020-10-04 06:57 UTC, huan commented on src/config.ts
> +export const SESSION_FILE_PATH: string = path.join(__dirname.replace('dist/src', ''), 'session.json')
When we need to store date in puppet, we should use memory card.

2020-10-05 11:49 UTC, huan commented
@univerone Please feel free to help yourself merge this PR when you feel it's OK.

After this PR has been merged, we can prepare to publish this repo to NPM soon.

2020-10-25 08:36 UTC, huan commented
ping @univerone 

Please take a look at my reviews and let me know what you think, thank you very much!

2020-10-27 02:00 UTC, univerone commented
> ping @univerone
> 
> Please take a look at my reviews and let me know what you think, thank you very much!

Sorry to reply late !  I'll solve this pr ASAP!

2020-10-27 04:49 UTC, univerone commented on package.json
> +    "faker": "^5.1.0",
faker is used in `src/mock/generator.ts`, maybe we could remove it after we implement relevant features,  and for now it can be used  as a placeholder

2020-10-27 06:22 UTC, huan commented on package.json
> +    "faker": "^5.1.0",
Ok, let's keep it for now and remove it later.

2020-11-11 05:00 UTC, huan requested changes
It's great to seeing your update!

Please follow my reviews, and also take a look at https://github.com/wechaty/wechaty-puppet/issues/125 , thank you very much!

2020-11-11 13:48 UTC, univerone commented on examples/ding-dong-bot.ts
> +const bot = new Wechaty({
Sure! It's resolved now

2020-11-12 03:50 UTC, huan approved these changes
LGTM

2020-11-12 03:50 UTC, merged

2020-11-12 03:53 UTC, huan commented
It is fantastic that we can have this PR been merged!

The Whatsapp puppet will help our Wechaty community to get a huge step forward, thank you @univerone for your effort!